import type { Metadata } from "next";
import localFont from "next/font/local";
import { LoaderProvider } from "@/context/LoaderContext";
import {AlertProvider} from "@/context/AlertContext";
import Alert from "@/components/Alert";
import GlobalLoader from "@/components/GlobalLoader";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "GymApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <LoaderProvider>
          <AlertProvider>
            {children}
            <GlobalLoader />
            <Alert />
          </AlertProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
